### ISSUE TITLE
Rippling Trustline

### ISSUE THREAD

**Issue by agmap** [kakoyla/icecold#1]
When adding a trustline rippling is enabled.

**Comment by kakoyla** [comment]
Are you sure rippling wasn't enabled in a prior transaction? Enabling Rippling requires an account set transaction, its not possible with a trust set transaction. I tried to recreate this issue with no luck.

**Comment by agmap** [comment]
First I activated a new wallet (sequence 0).
Then I added a trustline (sequence 1).
Bithomp explorer showed: rippling enabled, frozen no! (in the raw tx there is no entry with ripplingdisabled)
After that I used bithomp tools to create a trustline. 
Rippling is disabled. (in the raw tx in specification "ripplingdisabled: true")

**Comment by kakoyla** [comment]
Is this a testnet acct? Would you be willing to share acct number so I can look?

**Comment by agmap** [comment]
No, it is not testnet. 
Privacy is important to me
![01](https://user-images.githubusercontent.com/46416430/51082199-be349000-1702-11e9-91f8-110d4c2ed1ac.PNG)

![02](https://user-images.githubusercontent.com/46416430/51081940-b671ed00-16fc-11e9-88a6-41d4ed06550c.PNG)


In the raw TXid of the trustline I can find a entry "flags: 131072". So it also could be a bug of the bithomp explorer!

**Comment by kakoyla** [comment]
Oh OK, that's the issuer of the IOU you are seeing with Rippling enabled, not your a
Account. Look up bitstamp (rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B) and you will see.

**Comment by agmap** [comment]
No,
rippling was enabled on my account for the Trustline.

**Comment by kakoyla** [comment]
The screenshot you provided shows the trust line added transaction, in that tx it says rippling enabled, but that refers to the IOU issuers acct.

**Comment by agmap** [comment]
I want to create a trustline with rippling disabled. this was not possible

**Comment by kakoyla** [comment]
I understand what you are looking for now, i will see what i can do to fix it.

Thanks a lot for pointing this out, I wouldn't have noticed without you. Also found this post for anyone else who happens to wonder about this issue. https://www.xrpchat.com/topic/3124-noripple-flag/?do=findComment&comment=655700

**Comment by kakoyla** [comment]
Thanks again for bringing this to my attention, I thought you didn't know what you were talking about but it was me who was the problem, lesson learned. 
Added the flag on line 236 of the following, 
https://github.com/kakoyla/icecold/blob/master/src/components/TrustSet.vue
